type BrowserShellOptions = {
  defaultChromeHeight: number;
};

/**
 * Browser chrome rendered in the owning BrowserWindow while page contents live in a
 * BrowserView below it. The shell intentionally mirrors Codex's compact toolbar language:
 * one centered omnibox, quiet icon controls, native menus, a thin progress indicator,
 * and optional find/device strips that report their height back to the controller.
 */
export function codexBrowserShellHtml(options: BrowserShellOptions): string {
  return `<!doctype html>
<html lang="en" data-arivu-browser-shell="codex">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data: https: http:; script-src 'unsafe-inline'; style-src 'unsafe-inline'; form-action 'none'; base-uri 'none'">
  <title>Arivu Browser</title>
  <style>
    :root{color-scheme:dark;--bg:#171717;--raised:#202020;--hover:#2a2a2a;--line:#343434;--text:#f2f2f2;--muted:#a3a3a3;--accent:#5b9cf5;--danger:#ef766f;--toolbar-h:42px;--tabs-h:36px}
    *{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:var(--bg);color:var(--text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;font-size:13px;user-select:none}
    button,input,select{font:inherit}.shell{width:100%;background:var(--bg);border-bottom:1px solid var(--line)}
    .tabs-row{height:var(--tabs-h);display:flex;align-items:end;gap:2px;padding:4px 8px 0;min-width:0;background:#141414;-webkit-app-region:drag}
    .tabs{display:flex;flex:1;align-items:end;gap:2px;min-width:0;overflow:hidden;-webkit-app-region:no-drag}.tab{height:31px;min-width:92px;max-width:220px;display:grid;grid-template-columns:16px minmax(0,1fr) 22px;gap:6px;align-items:center;padding:0 4px 0 10px;border:0;border-radius:8px 8px 0 0;background:transparent;color:var(--muted);cursor:default;text-align:left}.tab:hover{background:#202020;color:var(--text)}.tab.active{background:var(--bg);color:var(--text)}
    .favicon{width:14px;height:14px;border-radius:3px;object-fit:contain}.favicon-fallback{display:grid;place-items:center;width:14px;height:14px;border-radius:4px;background:#343434;color:#bbb;font-size:9px;font-weight:700}.tab-title{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-weight:520}.tab-close{display:grid;place-items:center;width:22px;height:22px;border:0;border-radius:6px;background:transparent;color:inherit;opacity:0;cursor:pointer}.tab:hover .tab-close,.tab.active .tab-close{opacity:.72}.tab-close:hover{background:#3a3a3a;opacity:1}.new-tab,.tabs-menu{display:grid;place-items:center;width:28px;height:28px;margin:0 0 2px 2px;border:0;border-radius:7px;background:transparent;color:var(--muted);cursor:pointer;-webkit-app-region:no-drag}.new-tab:hover,.tabs-menu:hover{background:var(--hover);color:var(--text)}.tabs-menu{margin-left:auto}
    .toolbar{height:var(--toolbar-h);display:grid;grid-template-columns:auto minmax(180px,770px) auto;justify-content:center;align-items:center;gap:8px;padding:6px 8px;background:var(--bg)}.nav,.action{display:grid;place-items:center;width:28px;height:28px;border:0;border-radius:8px;background:transparent;color:var(--muted);cursor:pointer}.nav:hover:not(:disabled),.action:hover:not(:disabled){background:var(--hover);color:var(--text)}.nav:disabled,.action:disabled{opacity:.28;cursor:default}.nav-group,.action-group{display:flex;align-items:center;gap:1px}.action-group{gap:3px}
    svg{width:16px;height:16px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}.address-wrap{height:29px;min-width:0;display:flex;align-items:center;border:1px solid transparent;border-radius:10px;background:#222;transition:background .12s,border-color .12s}.address-wrap:hover{background:#292929}.address-wrap:focus-within{background:transparent;border-color:#4a4a4a}.site-info{display:grid;place-items:center;width:28px;height:27px;flex:0 0 auto;border:0;border-radius:9px 0 0 9px;background:transparent;color:var(--muted);cursor:pointer}.site-info:hover{background:#303030;color:var(--text)}.site-info.not-secure{width:auto;padding:0 8px;color:var(--danger);font-size:11px;font-weight:650;gap:5px;grid-auto-flow:column}.address-form{display:flex;min-width:0;flex:1;height:100%}.address{width:100%;min-width:0;border:0;outline:0;background:transparent;color:var(--text);padding:0 6px;font-size:13px;text-align:center;user-select:text}.address:focus{text-align:left}.address::placeholder{color:#777}.open-external{opacity:0}.address-wrap:hover .open-external,.address-wrap:focus-within .open-external{opacity:1}
    .progress{height:2px;overflow:hidden;background:transparent}.progress>i{display:block;width:38%;height:100%;background:var(--accent);transform:translateX(-110%);opacity:0}.progress.loading>i{opacity:1;animation:load 1.05s ease-in-out infinite}@keyframes load{0%{transform:translateX(-110%)}100%{transform:translateX(310%)}}
    .subbar{height:34px;display:flex;align-items:center;gap:7px;padding:3px 9px;border-top:1px solid var(--line);background:#1c1c1c;color:var(--muted)}.subbar[hidden]{display:none}.findbar{justify-content:flex-end}.find-input{width:min(280px,45vw);height:26px;border:1px solid var(--line);border-radius:7px;outline:0;background:#121212;color:var(--text);padding:0 8px;user-select:text}.find-input:focus{border-color:#555}.find-count{min-width:66px;font-size:11px;text-align:center}.sub-action{display:grid;place-items:center;width:26px;height:26px;border:0;border-radius:6px;background:transparent;color:var(--muted);cursor:pointer}.sub-action:hover{background:var(--hover);color:var(--text)}
    .devicebar{justify-content:center}.devicebar select,.devicebar input{height:26px;border:1px solid transparent;border-radius:7px;outline:0;background:#262626;color:var(--text)}.devicebar select{max-width:150px;padding:0 5px}.devicebar input{width:70px;padding:0 6px;text-align:center;user-select:text}.devicebar select:hover,.devicebar input:hover,.devicebar input:focus{border-color:#484848}.device-label{font-weight:550}.multiply{color:#777}
    .toast{position:fixed;right:12px;top:calc(var(--tabs-h) + var(--toolbar-h) + 8px);max-width:min(440px,calc(100vw - 24px));padding:9px 11px;border:1px solid var(--line);border-radius:9px;background:#252525;color:var(--text);box-shadow:0 16px 42px #0009;opacity:0;transform:translateY(-5px);pointer-events:none;transition:.16s;z-index:30}.toast.visible{opacity:1;transform:none}.toast.error{border-color:#7b3e3a;color:#ffaaa4}
    @media(max-width:760px){.toolbar{grid-template-columns:auto minmax(120px,1fr) auto}.tab{min-width:72px;max-width:150px}.action.optional{display:none}.tabs-row{padding-left:6px}.address{font-size:12px}}
    @media(prefers-reduced-motion:reduce){*,*::before,*::after{scroll-behavior:auto!important;transition:none!important;animation-duration:.001ms!important;animation-iteration-count:1!important}}
    @media(forced-colors:active){.shell,.address-wrap,.tab.active,.subbar{border-color:CanvasText}.nav:focus-visible,.action:focus-visible,.tab:focus-visible,.sub-action:focus-visible{outline:2px solid Highlight;outline-offset:1px}.progress>i{background:Highlight}}
  </style>
</head>
<body>
  <main class="shell" id="shell">
    <div class="tabs-row"><div class="tabs" id="tabs" role="tablist" aria-label="Browser tabs"></div><button class="tabs-menu" id="tabs-menu" aria-label="Show all tabs" title="Show all tabs">${icon("down")}</button><button class="new-tab" id="new-tab" aria-label="New tab" title="New tab (⌘T)">${icon("plus")}</button></div>
    <div class="toolbar" data-browser-sidebar-toolbar="true">
      <div class="nav-group"><button class="nav" id="back" aria-label="Back" title="Back (⌘[)">${icon("back")}</button><button class="nav" id="forward" aria-label="Forward" title="Forward (⌘])">${icon("forward")}</button><button class="nav" id="reload" aria-label="Reload" title="Reload (⌘R)">${icon("reload")}</button></div>
      <div class="address-wrap" id="address-wrap"><button class="site-info" id="site-info" aria-label="View site information" title="View site information">${icon("sliders")}</button><form class="address-form" id="address-form" autocomplete="off"><input class="address" id="address" name="url" type="text" inputmode="url" spellcheck="false" placeholder="Search or enter URL" aria-label="Address and search bar"></form><button class="action open-external" id="open-external" aria-label="Open in external browser" title="Open in external browser">${icon("external")}</button></div>
      <div class="action-group"><button class="action optional" id="screenshot" aria-label="Take a screenshot" title="Take a screenshot">${icon("camera")}</button><button class="action optional" id="downloads" aria-label="Downloads" title="Downloads">${icon("download")}</button><button class="action" id="options" aria-label="Browser options" title="Browser options">${icon("more")}</button></div>
    </div>
    <div class="subbar devicebar" id="devicebar" hidden><span class="device-label">Dimensions:</span><select id="device-preset" aria-label="Device preset"><option value="responsive">Responsive</option><option value="mobile-s">Mobile S</option><option value="mobile-m">Mobile M</option><option value="mobile-l">Mobile L</option><option value="tablet">Tablet</option><option value="laptop">Laptop</option><option value="desktop">Desktop</option><option value="4k">4K</option></select><input id="device-width" type="number" min="240" max="4096" aria-label="Viewport width"><span class="multiply">×</span><input id="device-height" type="number" min="160" max="4096" aria-label="Viewport height"><button class="sub-action" id="rotate-device" aria-label="Rotate viewport" title="Rotate viewport">${icon("rotate")}</button><button class="sub-action" id="close-device" aria-label="Exit device toolbar mode" title="Exit device toolbar mode">${icon("close")}</button></div>
    <div class="subbar findbar" id="findbar" hidden><input class="find-input" id="find-input" type="text" placeholder="Find in page" aria-label="Find in page"><span class="find-count" id="find-count">0 / 0</span><button class="sub-action" id="find-prev" aria-label="Previous match">${icon("up")}</button><button class="sub-action" id="find-next" aria-label="Next match">${icon("down")}</button><button class="sub-action" id="close-find" aria-label="Close find">${icon("close")}</button></div>
    <div class="progress" id="progress" aria-hidden="true"><i></i></div>
  </main>
  <div class="toast" id="toast" role="status" aria-live="polite"></div>
  <script>
    const DEFAULT_HEIGHT=${JSON.stringify(options.defaultChromeHeight)};
    let browserState=null;let lastHeight=0;let toastTimer;let draggedTabId="";
    const $=(id)=>document.getElementById(id);const shell=$("shell"),tabs=$("tabs"),address=$("address"),addressForm=$("address-form"),back=$("back"),forward=$("forward"),reload=$("reload"),progress=$("progress"),findbar=$("findbar"),findInput=$("find-input"),findCount=$("find-count"),devicebar=$("devicebar"),toast=$("toast");
    window.__ARIVU_BROWSER_APPLY_STATE__=(state)=>{browserState=state;render(state)};
    function render(state){const items=Array.isArray(state.tabs)?state.tabs:[];tabs.replaceChildren();for(const tab of items){const button=document.createElement("button");button.type="button";button.className="tab"+(tab.id===state.activeTabId?" active":"");button.role="tab";button.draggable=true;button.dataset.tabId=tab.id;button.setAttribute("aria-selected",tab.id===state.activeTabId?"true":"false");button.title=tab.title||tab.url||"New tab";button.addEventListener("click",()=>send("select-tab",{id:tab.id}));button.addEventListener("auxclick",(event)=>{if(event.button===1)send("close-tab",{id:tab.id})});button.addEventListener("dragstart",()=>{draggedTabId=tab.id});button.addEventListener("dragover",(event)=>event.preventDefault());button.addEventListener("drop",(event)=>{event.preventDefault();if(draggedTabId&&draggedTabId!==tab.id)send("reorder-tab",{id:draggedTabId,before:tab.id})});const favicon=tab.faviconUrl?Object.assign(document.createElement("img"),{className:"favicon",src:tab.faviconUrl,alt:""}):Object.assign(document.createElement("span"),{className:"favicon-fallback",textContent:(host(tab.url)||"A").charAt(0).toUpperCase()});const title=Object.assign(document.createElement("span"),{className:"tab-title",textContent:tab.title||host(tab.url)||"New tab"});const close=Object.assign(document.createElement("button"),{type:"button",className:"tab-close",ariaLabel:"Close tab",innerHTML:${JSON.stringify(icon("close"))}});close.addEventListener("click",(event)=>{event.stopPropagation();send("close-tab",{id:tab.id})});button.append(favicon,title,close);tabs.append(button)}
      const chrome=state.chrome||{};if(document.activeElement!==address)address.value=state.url||"";back.disabled=!state.canGoBack;forward.disabled=!state.canGoForward;reload.innerHTML=state.loading?${JSON.stringify(icon("stop"))}:${JSON.stringify(icon("reload"))};reload.title=state.loading?"Stop":"Reload (⌘R)";progress.classList.toggle("loading",Boolean(state.loading));
      const secure=security(state.url,chrome.securityState);const siteInfo=$("site-info");siteInfo.classList.toggle("not-secure",secure.notSecure);siteInfo.innerHTML=secure.notSecure?${JSON.stringify(icon("warning"))}+"<span>Not secure</span>":${JSON.stringify(icon("sliders"))};siteInfo.ariaLabel=secure.notSecure?"Not secure, view site information":"View site information";
      findbar.hidden=!chrome.findOpen;devicebar.hidden=!chrome.device?.enabled;if(chrome.findOpen&&document.activeElement!==findInput)findInput.value=chrome.findQuery||"";findCount.textContent=(chrome.findActiveMatch||0)+" / "+(chrome.findMatches||0);if(chrome.device){$("device-preset").value=chrome.device.preset||"responsive";$("device-width").value=chrome.device.width||390;$("device-height").value=chrome.device.height||844}requestLayout();if(chrome.notice&&chrome.notice.id!==window.__lastNoticeId){window.__lastNoticeId=chrome.notice.id;showToast(chrome.notice.message,chrome.notice.error)}if(state.lastError)showToast(state.lastError,true)}
    function requestLayout(){requestAnimationFrame(()=>{const height=Math.max(DEFAULT_HEIGHT,Math.ceil(shell.getBoundingClientRect().height));if(height!==lastHeight){lastHeight=height;send("layout",{height})}})}
    addressForm.addEventListener("submit",(event)=>{event.preventDefault();const value=address.value.trim();if(value)send("navigate",{id:browserState?.activeTabId||"",url:value})});address.addEventListener("focus",()=>address.select());
    back.onclick=()=>send("back",active());forward.onclick=()=>send("forward",active());reload.onclick=()=>send(browserState?.loading?"stop":"reload",active());$("new-tab").onclick=()=>send("new-tab");$("tabs-menu").onclick=()=>send("tabs-menu");$("open-external").onclick=()=>send("open-external",active());$("site-info").onclick=()=>send("site-info",active());$("screenshot").onclick=()=>send("capture-screenshot",active());$("downloads").onclick=()=>send("downloads",active());$("options").onclick=()=>send("options",active());
    findInput.addEventListener("input",()=>send("find",{...active(),query:findInput.value,forward:"true"}));findInput.addEventListener("keydown",(event)=>{if(event.key==="Enter"){event.preventDefault();send("find",{...active(),query:findInput.value,forward:String(!event.shiftKey)})}else if(event.key==="Escape")send("close-find",active())});$("find-prev").onclick=()=>send("find",{...active(),query:findInput.value,forward:"false"});$("find-next").onclick=()=>send("find",{...active(),query:findInput.value,forward:"true"});$("close-find").onclick=()=>send("close-find",active());
    $("device-preset").onchange=(event)=>send("device-preset",{...active(),preset:event.target.value});for(const id of ["device-width","device-height"]){$(id).onchange=()=>send("device-size",{...active(),width:$("device-width").value,height:$("device-height").value})}$("rotate-device").onclick=()=>send("rotate-device",active());$("close-device").onclick=()=>send("toggle-device",active());
    window.addEventListener("keydown",(event)=>{const mod=event.metaKey||event.ctrlKey;if(event.ctrlKey&&event.key==="Tab"){event.preventDefault();send("cycle-tab",{direction:event.shiftKey?"-1":"1"})}else if(mod&&event.key.toLowerCase()==="l"){event.preventDefault();address.focus();address.select()}else if(mod&&event.key.toLowerCase()==="t"){event.preventDefault();send("new-tab")}else if(mod&&event.key.toLowerCase()==="w"){event.preventDefault();send("close-tab",active())}else if(mod&&event.key.toLowerCase()==="f"){event.preventDefault();send("open-find",active())}else if(mod&&event.key.toLowerCase()==="r"){event.preventDefault();send(event.shiftKey?"hard-reload":"reload",active())}});
    function active(){return{id:browserState?.activeTabId||""}}function send(action,params={}){const url=new URL("arivu-browser://"+action);for(const[key,value]of Object.entries(params))if(value!==undefined&&value!==null&&String(value)!=="")url.searchParams.set(key,String(value));window.location.href=url.href}function host(value){try{return new URL(value).hostname}catch{return""}}function security(value,state){if(state==="certificate-error")return{notSecure:true};try{const url=new URL(value);return{notSecure:url.protocol==="http:"&&!['localhost','127.0.0.1','::1'].includes(url.hostname)}}catch{return{notSecure:false}}}function showToast(message,error=false){clearTimeout(toastTimer);toast.textContent=message;toast.className="toast visible"+(error?" error":"");toastTimer=setTimeout(()=>toast.className="toast",3600)}
  </script>
</body></html>`;
}

function icon(name: string): string {
  const paths: Record<string, string> = {
    back: '<path d="m14 5-7 7 7 7"/>',
    forward: '<path d="m10 5 7 7-7 7"/>',
    reload: '<path d="M20 11a8 8 0 1 0-2.3 5.7"/><path d="M20 4v7h-7"/>',
    stop: '<path d="M7 7h10v10H7z"/>',
    plus: '<path d="M12 5v14M5 12h14"/>',
    close: '<path d="m7 7 10 10M17 7 7 17"/>',
    external: '<path d="M14 4h6v6M20 4l-9 9"/><path d="M18 13v6a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h6"/>',
    sliders: '<path d="M4 7h10M18 7h2M4 17h2M10 17h10"/><circle cx="16" cy="7" r="2"/><circle cx="8" cy="17" r="2"/>',
    warning: '<path d="M12 4 3.5 19h17L12 4Z"/><path d="M12 9v4M12 16h.01"/>',
    camera: '<path d="M4 8h3l2-3h6l2 3h3v11H4V8Z"/><circle cx="12" cy="13" r="3"/>',
    download: '<path d="M12 3v12M7 10l5 5 5-5M5 20h14"/>',
    more: '<circle cx="5" cy="12" r="1" fill="currentColor" stroke="none"/><circle cx="12" cy="12" r="1" fill="currentColor" stroke="none"/><circle cx="19" cy="12" r="1" fill="currentColor" stroke="none"/>',
    rotate: '<path d="M20 7v5h-5"/><path d="M18.5 15A7 7 0 1 1 19 8l1 4"/>',
    up: '<path d="m7 14 5-5 5 5"/>',
    down: '<path d="m7 10 5 5 5-5"/>'
  };
  return `<svg viewBox="0 0 24 24" aria-hidden="true">${paths[name] ?? ""}</svg>`;
}
