type BrowserShellOptions = {
  defaultChromeHeight: number;
};

/**
 * Browser chrome rendered in the owning BrowserWindow while page contents live in a
 * BrowserView below it. The shell intentionally mirrors Codex's compact toolbar language:
 * one centered omnibox, quiet icon controls, native menus, a thin progress indicator,
 * and optional find/device strips that report their height back to the controller.
 */
export function codexBrowserShellHtml(options: BrowserShellOptions): string {
  return `<!doctype html>
<html lang="en" data-arivu-browser-shell="codex">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data: https: http:; script-src 'unsafe-inline'; style-src 'unsafe-inline'; form-action 'none'; base-uri 'none'">
  <title>Arivu Browser</title>
  <style>
    :root{color-scheme:dark;--bg:#171717;--raised:#202020;--hover:#2a2a2a;--line:#343434;--text:#f2f2f2;--muted:#a3a3a3;--accent:#5b9cf5;--danger:#ef766f;--toolbar-h:42px;--tabs-h:36px}
    *{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:var(--bg);color:var(--text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;font-size:13px;user-select:none}
    button,input,select{font:inherit}.shell{width:100%;background:var(--bg);border-bottom:1px solid var(--line)}
    .tabs-row{height:var(--tabs-h);display:flex;align-items:end;gap:2px;padding:4px 8px 0;min-width:0;background:#141414;-webkit-app-region:drag}
    .tabs{display:flex;flex:1;align-items:end;gap:2px;min-width:0;overflow:hidden;-webkit-app-region:no-drag}.tab{height:31px;min-width:92px;max-width:220px;display:grid;grid-template-columns:16px minmax(0,1fr) 22px;gap:6px;align-items:center;padding:0 4px 0 10px;border:0;border-radius:8px 8px 0 0;background:transparent;color:var(--muted);cursor:default;text-align:left}.tab:hover{background:#202020;color:var(--text)}.tab.active{background:var(--bg);color:var(--text)}
    .tab.agent-working{position:relative}.tab.agent-working::after{content:"";position:absolute;left:10px;right:10px;bottom:2px;height:2px;border-radius:2px;background:#3d8e79;animation:agentpulse 1.6s ease-in-out infinite}@keyframes agentpulse{0%,100%{opacity:.35}50%{opacity:1}}
    .agent-chip{height:26px;margin:0 4px 3px;padding:0 10px;border:1px solid #3d8e79;border-radius:13px;background:#203c35;color:#d9fff3;font-size:12px;cursor:pointer;white-space:nowrap;-webkit-app-region:no-drag}.agent-chip:hover{background:#286d5c}.agent-chip[hidden]{display:none}
    .favicon{width:14px;height:14px;border-radius:3px;object-fit:contain}.favicon-fallback{display:grid;place-items:center;width:14px;height:14px;border-radius:4px;background:#343434;color:#bbb;font-size:9px;font-weight:700}.tab-title{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-weight:520}.tab-close{display:grid;place-items:center;width:22px;height:22px;border:0;border-radius:6px;background:transparent;color:inherit;opacity:0;cursor:pointer}.tab:hover .tab-close,.tab.active .tab-close{opacity:.72}.tab-close:hover{background:#3a3a3a;opacity:1}.new-tab,.tabs-menu{display:grid;place-items:center;width:28px;height:28px;margin:0 0 2px 2px;border:0;border-radius:7px;background:transparent;color:var(--muted);cursor:pointer;-webkit-app-region:no-drag}.new-tab:hover,.tabs-menu:hover{background:var(--hover);color:var(--text)}.tabs-menu{margin-left:auto}
    .toolbar{height:var(--toolbar-h);display:grid;grid-template-columns:auto minmax(180px,770px) auto;justify-content:center;align-items:center;gap:8px;padding:6px 8px;background:var(--bg)}.nav,.action{display:grid;place-items:center;width:28px;height:28px;border:0;border-radius:8px;background:transparent;color:var(--muted);cursor:pointer}.nav:hover:not(:disabled),.action:hover:not(:disabled){background:var(--hover);color:var(--text)}.nav:disabled,.action:disabled{opacity:.28;cursor:default}.nav-group,.action-group{display:flex;align-items:center;gap:1px}.action-group{gap:3px}
    svg{width:16px;height:16px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}.address-wrap{height:29px;min-width:0;display:flex;align-items:center;border:1px solid transparent;border-radius:10px;background:#222;transition:background .12s,border-color .12s}.address-wrap:hover{background:#292929}.address-wrap:focus-within{background:transparent;border-color:#4a4a4a}.site-info{display:grid;place-items:center;width:28px;height:27px;flex:0 0 auto;border:0;border-radius:9px 0 0 9px;background:transparent;color:var(--muted);cursor:pointer}.site-info:hover{background:#303030;color:var(--text)}.site-info.not-secure{width:auto;padding:0 8px;color:var(--danger);font-size:11px;font-weight:650;gap:5px;grid-auto-flow:column}.address-form{display:flex;min-width:0;flex:1;height:100%}.address{width:100%;min-width:0;border:0;outline:0;background:transparent;color:var(--text);padding:0 6px;font-size:13px;text-align:center;user-select:text}.address:focus{text-align:left}.address::placeholder{color:#777}.open-external{opacity:0}.address-wrap:hover .open-external,.address-wrap:focus-within .open-external{opacity:1}
    .progress{height:2px;overflow:hidden;background:transparent}.progress>i{display:block;width:38%;height:100%;background:var(--accent);transform:translateX(-110%);opacity:0}.progress.loading>i{opacity:1;animation:load 1.05s ease-in-out infinite}@keyframes load{0%{transform:translateX(-110%)}100%{transform:translateX(310%)}}
    .subbar{height:34px;display:flex;align-items:center;gap:7px;padding:3px 9px;border-top:1px solid var(--line);background:#1c1c1c;color:var(--muted)}.subbar[hidden]{display:none}.findbar{justify-content:flex-end}.find-input{width:min(280px,45vw);height:26px;border:1px solid var(--line);border-radius:7px;outline:0;background:#121212;color:var(--text);padding:0 8px;user-select:text}.find-input:focus{border-color:#555}.find-count{min-width:66px;font-size:11px;text-align:center}.sub-action{display:grid;place-items:center;width:26px;height:26px;border:0;border-radius:6px;background:transparent;color:var(--muted);cursor:pointer}.sub-action:hover{background:var(--hover);color:var(--text)}
    .devicebar{justify-content:center}.devicebar select,.devicebar input{height:26px;border:1px solid transparent;border-radius:7px;outline:0;background:#262626;color:var(--text)}.devicebar select{max-width:150px;padding:0 5px}.devicebar input{width:70px;padding:0 6px;text-align:center;user-select:text}.devicebar select:hover,.devicebar input:hover,.devicebar input:focus{border-color:#484848}.device-label{font-weight:550}.multiply{color:#777}
    .reviewbar{min-height:142px;max-height:270px;display:grid;grid-template-columns:210px minmax(240px,1fr) minmax(260px,1.15fr);align-items:stretch;gap:0;padding:0;border-top:1px solid var(--line);background:#1b1b1b}.reviewbar[hidden]{display:none}.review-column{min-width:0;padding:10px;border-right:1px solid var(--line);overflow:auto}.review-column:last-child{border-right:0}.review-heading{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:8px}.review-heading strong{font-size:12px}.review-modes{display:flex;gap:4px}.review-mode{height:28px;border:1px solid var(--line);border-radius:7px;background:#242424;color:var(--muted);padding:0 8px;cursor:pointer}.review-mode.active,.review-mode:hover{border-color:#4a7f72;background:#203c35;color:#d9fff3}.annotation-list{display:grid;gap:4px}.annotation-item{width:100%;display:flex;align-items:center;gap:7px;padding:7px;border:1px solid transparent;border-radius:7px;background:transparent;color:var(--muted);text-align:left;cursor:pointer}.annotation-item:hover,.annotation-item.active{border-color:var(--line);background:#242424;color:var(--text)}.annotation-item span{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.annotation-empty{padding:16px 6px;color:#777;font-size:11px}.review-note{width:100%;height:64px;resize:vertical;border:1px solid var(--line);border-radius:7px;background:#121212;color:var(--text);padding:8px;outline:0;user-select:text}.review-note:focus{border-color:#555}.review-actions{display:flex;align-items:center;gap:6px;margin-top:7px;flex-wrap:wrap}.review-button{height:28px;border:1px solid var(--line);border-radius:7px;background:#282828;color:var(--text);padding:0 9px;cursor:pointer}.review-button:hover{background:#333}.review-button.primary{border-color:#3d8e79;background:#286d5c}.review-button.danger{color:#ffaaa4}.design-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:6px}.design-field{display:grid;gap:3px;color:#888;font-size:10px}.design-field input,.design-field select{width:100%;height:27px;border:1px solid var(--line);border-radius:6px;background:#121212;color:var(--text);padding:0 6px;outline:0;user-select:text}.design-field input[type=color]{padding:2px}.agent-transfer{display:flex;align-items:center;gap:6px;margin-top:9px;padding-top:8px;border-top:1px solid var(--line);font-size:11px;color:#888}.agent-transfer span{min-width:0;flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.device-scale{font-size:11px;color:#888}
    .toast{position:fixed;right:12px;top:calc(var(--tabs-h) + var(--toolbar-h) + 8px);max-width:min(440px,calc(100vw - 24px));padding:9px 11px;border:1px solid var(--line);border-radius:9px;background:#252525;color:var(--text);box-shadow:0 16px 42px #0009;opacity:0;transform:translateY(-5px);pointer-events:none;transition:.16s;z-index:30}.toast.visible{opacity:1;transform:none}.toast.error{border-color:#7b3e3a;color:#ffaaa4}
    button:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible{outline:2px solid var(--accent);outline-offset:2px}@media(max-width:900px){.reviewbar{grid-template-columns:180px 1fr}.review-column.design{grid-column:1/-1;border-top:1px solid var(--line)}.design-grid{grid-template-columns:repeat(4,minmax(0,1fr))}}@media(max-width:760px){.toolbar{grid-template-columns:auto minmax(120px,1fr) auto}.tab{min-width:72px;max-width:150px}.action.optional{display:none}.tabs-row{padding-left:6px}.address{font-size:12px}.reviewbar{grid-template-columns:1fr;max-height:330px}.review-column{border-right:0;border-bottom:1px solid var(--line)}.design-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
    @media(prefers-color-scheme:light){:root{color-scheme:light;--bg:#f7f7f6;--raised:#fff;--hover:#e9e9e7;--line:#d7d7d4;--text:#1d1d1c;--muted:#696965;--accent:#326cab;--danger:#a72e29}.tabs-row{background:#ececea}.tab.active,.toolbar,.shell{background:var(--bg)}.address-wrap,.review-mode,.review-button{background:#fff}.subbar,.reviewbar{background:#f2f2f0}.review-column{border-color:var(--line)}.review-note,.design-field input,.design-field select{background:#fff}.toast{background:#fff;box-shadow:0 16px 42px #0002}}
    @media(prefers-reduced-motion:reduce){*,*::before,*::after{scroll-behavior:auto!important;transition:none!important;animation-duration:.001ms!important;animation-iteration-count:1!important}}
    @media(forced-colors:active){.shell,.address-wrap,.tab.active,.subbar{border-color:CanvasText}.nav:focus-visible,.action:focus-visible,.tab:focus-visible,.sub-action:focus-visible{outline:2px solid Highlight;outline-offset:1px}.progress>i{background:Highlight}}
  </style>
</head>
<body>
  <main class="shell" id="shell">
    <div class="tabs-row"><div class="tabs" id="tabs" role="tablist" aria-label="Browser tabs"></div><button class="agent-chip" id="agent-chip" type="button" hidden></button><button class="tabs-menu" id="tabs-menu" aria-label="Show all tabs" title="Show all tabs">${icon("down")}</button><button class="new-tab" id="new-tab" aria-label="New tab" title="New tab (⌘T)">${icon("plus")}</button></div>
    <div class="toolbar" data-browser-sidebar-toolbar="true">
      <div class="nav-group"><button class="nav" id="back" aria-label="Back" title="Back (⌘[)">${icon("back")}</button><button class="nav" id="forward" aria-label="Forward" title="Forward (⌘])">${icon("forward")}</button><button class="nav" id="reload" aria-label="Reload" title="Reload (⌘R)">${icon("reload")}</button></div>
      <div class="address-wrap" id="address-wrap"><button class="site-info" id="site-info" aria-label="View site information" title="View site information">${icon("sliders")}</button><form class="address-form" id="address-form" autocomplete="off"><input class="address" id="address" name="url" type="text" inputmode="url" spellcheck="false" placeholder="Search or enter URL" aria-label="Address and search bar"></form><button class="action open-external" id="open-external" aria-label="Open in external browser" title="Open in external browser">${icon("external")}</button></div>
      <div class="action-group"><button class="action" id="review" aria-label="Review and comment" title="Review and comment">${icon("comment")}</button><button class="action optional" id="screenshot" aria-label="Take a screenshot" title="Take a screenshot">${icon("camera")}</button><button class="action optional" id="downloads" aria-label="Downloads" title="Downloads">${icon("download")}</button><button class="action" id="options" aria-label="Browser options" title="Browser options">${icon("more")}</button></div>
    </div>
    <div class="subbar devicebar" id="devicebar" hidden><span class="device-label">Dimensions:</span><select id="device-preset" aria-label="Device preset"><option value="responsive">Responsive</option><option value="mobile-s">Mobile S</option><option value="mobile-m">Mobile M</option><option value="mobile-l">Mobile L</option><option value="tablet">Tablet</option><option value="laptop">Laptop</option><option value="desktop">Desktop</option><option value="4k">4K</option></select><input id="device-width" type="number" min="240" max="4096" aria-label="Viewport width"><span class="multiply">×</span><input id="device-height" type="number" min="160" max="4096" aria-label="Viewport height"><button class="sub-action" id="rotate-device" aria-label="Rotate viewport" title="Rotate viewport">${icon("rotate")}</button><button class="sub-action" id="close-device" aria-label="Exit device toolbar mode" title="Exit device toolbar mode">${icon("close")}</button></div>
    <div class="subbar findbar" id="findbar" hidden><input class="find-input" id="find-input" type="text" placeholder="Find in page" aria-label="Find in page"><span class="find-count" id="find-count">0 / 0</span><button class="sub-action" id="find-prev" aria-label="Previous match">${icon("up")}</button><button class="sub-action" id="find-next" aria-label="Next match">${icon("down")}</button><button class="sub-action" id="close-find" aria-label="Close find">${icon("close")}</button></div>
    <aside class="reviewbar" id="reviewbar" aria-label="Browser review" hidden>
      <section class="review-column"><div class="review-heading"><strong>Review</strong><div class="review-modes"><button class="review-mode" data-review-mode="element" title="Select element">Element</button><button class="review-mode" data-review-mode="region" title="Capture region">Region</button></div></div><div class="annotation-list" id="annotation-list"></div><div class="agent-transfer"><span id="agent-tab-status">No background agent page</span><button class="review-button" id="transfer-agent-tab" type="button">Transfer</button></div></section>
      <section class="review-column"><div class="review-heading"><strong>Comment</strong><span id="selection-label"></span></div><textarea class="review-note" id="review-note" maxlength="4000" placeholder="Describe what should change" aria-label="Browser annotation comment"></textarea><div class="review-actions"><button class="review-button" id="hold-original" type="button">Hold original</button><button class="review-button danger" id="discard-annotation" type="button">Discard</button><button class="review-button primary" id="send-annotations" type="button">Send to Arivu</button></div></section>
      <section class="review-column design"><div class="review-heading"><strong>Design adjustments</strong><span class="device-scale" id="device-scale"></span></div><div class="design-grid"><label class="design-field">Text<input data-design="color" type="color" value="#111111"></label><label class="design-field">Background<input data-design="backgroundColor" type="color" value="#ffffff"></label><label class="design-field">Font size<input data-design="fontSize" type="text" placeholder="16px"></label><label class="design-field">Weight<select data-design="fontWeight"><option value="">Keep</option><option>400</option><option>500</option><option>600</option><option>700</option></select></label><label class="design-field">Radius<input data-design="borderRadius" type="text" placeholder="8px"></label><label class="design-field">Border<input data-design="borderWidth" type="text" placeholder="1px"></label><label class="design-field">Width<input data-design="width" type="text" placeholder="auto"></label><label class="design-field">Height<input data-design="height" type="text" placeholder="auto"></label><label class="design-field">Layout<select data-design="display"><option value="">Keep</option><option>block</option><option>flex</option><option>grid</option><option>inline-flex</option></select></label><label class="design-field">Direction<select data-design="flexDirection"><option value="">Keep</option><option>row</option><option>column</option></select></label><label class="design-field">Gap<input data-design="gap" type="text" placeholder="8px"></label><label class="design-field">Padding<input data-design="padding" type="text" placeholder="12px"></label><label class="design-field">Margin<input data-design="margin" type="text" placeholder="0"></label></div></section>
    </aside>
    <div class="progress" id="progress" aria-hidden="true"><i></i></div>
  </main>
  <div class="toast" id="toast" role="status" aria-live="polite"></div>
  <script>
    const DEFAULT_HEIGHT=${JSON.stringify(options.defaultChromeHeight)};
    let browserState=null;let lastHeight=0;let toastTimer;let draggedTabId="";let reviewOpen=false;
    const $=(id)=>document.getElementById(id);const shell=$("shell"),tabs=$("tabs"),address=$("address"),addressForm=$("address-form"),back=$("back"),forward=$("forward"),reload=$("reload"),progress=$("progress"),findbar=$("findbar"),findInput=$("find-input"),findCount=$("find-count"),devicebar=$("devicebar"),reviewbar=$("reviewbar"),reviewNote=$("review-note"),annotationList=$("annotation-list"),toast=$("toast");
    window.__ARIVU_BROWSER_APPLY_STATE__=(state)=>{browserState=state;render(state)};
    function render(state){const items=Array.isArray(state.tabs)?state.tabs:[];tabs.replaceChildren();for(const tab of items){const button=document.createElement("button");button.type="button";button.className="tab"+(tab.id===state.activeTabId?" active":"");button.role="tab";button.tabIndex=tab.id===state.activeTabId?0:-1;button.draggable=true;button.dataset.tabId=tab.id;button.setAttribute("aria-selected",tab.id===state.activeTabId?"true":"false");button.title=tab.title||tab.url||"New tab";if(tab.agentActive){button.classList.add("agent-working");button.title=(tab.title||tab.url||"New tab")+" — agent working";}button.addEventListener("click",()=>send("select-tab",{id:tab.id}));button.addEventListener("keydown",(event)=>{if(["ArrowLeft","ArrowRight","Home","End"].includes(event.key)){event.preventDefault();if(event.key==="Home")send("select-tab",{id:items[0]?.id});else if(event.key==="End")send("select-tab",{id:items.at(-1)?.id});else send("cycle-tab",{direction:event.key==="ArrowLeft"?"-1":"1"})}});button.addEventListener("auxclick",(event)=>{if(event.button===1)send("close-tab",{id:tab.id})});button.addEventListener("dragstart",()=>{draggedTabId=tab.id});button.addEventListener("dragover",(event)=>event.preventDefault());button.addEventListener("drop",(event)=>{event.preventDefault();if(draggedTabId&&draggedTabId!==tab.id)send("reorder-tab",{id:draggedTabId,before:tab.id})});const favicon=tab.faviconUrl?Object.assign(document.createElement("img"),{className:"favicon",src:tab.faviconUrl,alt:""}):Object.assign(document.createElement("span"),{className:"favicon-fallback",textContent:(host(tab.url)||"A").charAt(0).toUpperCase()});const title=Object.assign(document.createElement("span"),{className:"tab-title",textContent:tab.title||host(tab.url)||"New tab"});const close=Object.assign(document.createElement("button"),{type:"button",className:"tab-close",ariaLabel:"Close tab",innerHTML:${JSON.stringify(icon("close"))}});close.addEventListener("click",(event)=>{event.stopPropagation();send("close-tab",{id:tab.id})});button.append(favicon,title,close);tabs.append(button)}
      const chrome=state.chrome||{};if(document.activeElement!==address)address.value=state.url||"";back.disabled=!state.canGoBack;forward.disabled=!state.canGoForward;reload.innerHTML=state.loading?${JSON.stringify(icon("stop"))}:${JSON.stringify(icon("reload"))};reload.title=state.loading?"Stop":"Reload (⌘R)";progress.classList.toggle("loading",Boolean(state.loading));
      const secure=security(state.url,chrome.securityState);const siteInfo=$("site-info");siteInfo.classList.toggle("not-secure",secure.notSecure);siteInfo.innerHTML=secure.notSecure?${JSON.stringify(icon("warning"))}+"<span>Not secure</span>":${JSON.stringify(icon("sliders"))};siteInfo.ariaLabel=secure.notSecure?"Not secure, view site information":"View site information";
      const agentWork=chrome.agentWork;const agentChip=$("agent-chip");if(agentWork){agentChip.hidden=false;agentChip.textContent=agentWork.watching?"Hide agent view":"Watch agent";agentChip.title=agentWork.watching?"Return to your tab — the agent keeps working in the background":"Show the tab the agent is working on"+(agentWork.title?": "+agentWork.title:"");agentChip.onclick=()=>send(agentWork.watching?"hide-agent":"watch-agent",agentWork.watching?{}:{id:agentWork.tabId})}else{agentChip.hidden=true}
      findbar.hidden=!chrome.findOpen;devicebar.hidden=!chrome.device?.enabled;reviewbar.hidden=!reviewOpen;if(chrome.findOpen&&document.activeElement!==findInput)findInput.value=chrome.findQuery||"";findCount.textContent=(chrome.findActiveMatch||0)+" / "+(chrome.findMatches||0);if(chrome.device){$("device-preset").value=chrome.device.preset||"responsive";$("device-width").value=chrome.device.width||390;$("device-height").value=chrome.device.height||844;$("device-scale").textContent=chrome.device.enabled&&chrome.device.scale<1?Math.round(chrome.device.scale*100)+"% preview":""}renderReview(chrome);requestLayout();if(chrome.notice&&chrome.notice.id!==window.__lastNoticeId){window.__lastNoticeId=chrome.notice.id;showToast(chrome.notice.message,chrome.notice.error)}if(state.lastError)showToast(state.lastError,true)}
    function renderReview(chrome){const annotations=Array.isArray(chrome.annotations)?chrome.annotations:[];if(chrome.activeAnnotationId&&chrome.activeAnnotationId!==window.__lastAnnotationId){window.__lastAnnotationId=chrome.activeAnnotationId;reviewOpen=true;reviewbar.hidden=false;$("review").setAttribute("aria-pressed","true")}annotationList.replaceChildren();for(const annotation of annotations){const button=document.createElement("button");button.type="button";button.className="annotation-item"+(annotation.id===chrome.activeAnnotationId?" active":"");button.innerHTML=${JSON.stringify(icon("comment"))};const label=document.createElement("span");label.textContent=annotation.comment||annotation.label||annotation.kind;button.append(label);button.onclick=()=>send("annotation-select",{id:annotation.id});annotationList.append(button)}if(!annotations.length){const empty=document.createElement("div");empty.className="annotation-empty";empty.textContent="Select an element or region to start.";annotationList.append(empty)}const active=annotations.find((annotation)=>annotation.id===chrome.activeAnnotationId);if(document.activeElement!==reviewNote)reviewNote.value=active?.comment||"";reviewNote.disabled=!active;$("selection-label").textContent=active?.label||"";$("discard-annotation").disabled=!active;$("hold-original").disabled=!active?.designPatch;$("send-annotations").disabled=!annotations.length;for(const field of document.querySelectorAll("[data-design]")){field.disabled=!active?.selector;const value=active?.designPatch?.[field.dataset.design]??active?.computedStyle?.[field.dataset.design];if(value&&document.activeElement!==field){if(field.type==="color"){const hex=rgbToHex(value);if(hex)field.value=hex}else field.value=value}}for(const button of document.querySelectorAll("[data-review-mode]"))button.classList.toggle("active",button.dataset.reviewMode===chrome.annotationMode);const agent=chrome.backgroundAgent||{};$("agent-tab-status").textContent=agent.url?(agent.loading?"Agent loading: ":"Agent: ")+(agent.title||host(agent.url)):"No background agent page";$("transfer-agent-tab").textContent=agent.url?"Adopt":"Send tab"}
    function requestLayout(){requestAnimationFrame(()=>{const height=Math.max(DEFAULT_HEIGHT,Math.ceil(shell.getBoundingClientRect().height));if(height!==lastHeight){lastHeight=height;send("layout",{height})}})}
    addressForm.addEventListener("submit",(event)=>{event.preventDefault();const value=address.value.trim();if(value)send("navigate",{id:browserState?.activeTabId||"",url:value})});address.addEventListener("focus",()=>address.select());
    back.onclick=()=>send("back",active());forward.onclick=()=>send("forward",active());reload.onclick=()=>send(browserState?.loading?"stop":"reload",active());$("new-tab").onclick=()=>send("new-tab");$("tabs-menu").onclick=()=>send("tabs-menu");$("open-external").onclick=()=>send("open-external",active());$("site-info").onclick=()=>send("site-info",active());$("screenshot").onclick=()=>send("capture-screenshot",active());$("downloads").onclick=()=>send("downloads",active());$("options").onclick=()=>send("options",active());
    $("review").onclick=()=>{reviewOpen=!reviewOpen;reviewbar.hidden=!reviewOpen;$("review").setAttribute("aria-pressed",String(reviewOpen));requestLayout()};for(const button of document.querySelectorAll("[data-review-mode]")){button.onclick=()=>send("annotation-mode",{mode:button.dataset.reviewMode})}reviewNote.addEventListener("change",()=>send("annotation-comment",{id:browserState?.chrome?.activeAnnotationId||"",comment:reviewNote.value}));for(const field of document.querySelectorAll("[data-design]")){field.addEventListener("change",()=>send("annotation-design",{[field.dataset.design]:field.value}))}const hold=$("hold-original");hold.addEventListener("pointerdown",()=>send("annotation-preview",{mode:"original"}));for(const eventName of ["pointerup","pointercancel","pointerleave"]){hold.addEventListener(eventName,()=>send("annotation-preview",{mode:"preview"}))}$("discard-annotation").onclick=()=>send("annotation-discard",{id:browserState?.chrome?.activeAnnotationId||""});$("send-annotations").onclick=()=>send("annotation-send",{id:browserState?.chrome?.activeAnnotationId||"",comment:reviewNote.value});$("transfer-agent-tab").onclick=()=>send(browserState?.chrome?.backgroundAgent?.url?"adopt-agent-tab":"send-tab-to-agent");
    findInput.addEventListener("input",()=>send("find",{...active(),query:findInput.value,forward:"true"}));findInput.addEventListener("keydown",(event)=>{if(event.key==="Enter"){event.preventDefault();send("find",{...active(),query:findInput.value,forward:String(!event.shiftKey)})}else if(event.key==="Escape")send("close-find",active())});$("find-prev").onclick=()=>send("find",{...active(),query:findInput.value,forward:"false"});$("find-next").onclick=()=>send("find",{...active(),query:findInput.value,forward:"true"});$("close-find").onclick=()=>send("close-find",active());
    $("device-preset").onchange=(event)=>send("device-preset",{...active(),preset:event.target.value});for(const id of ["device-width","device-height"]){$(id).onchange=()=>send("device-size",{...active(),width:$("device-width").value,height:$("device-height").value})}$("rotate-device").onclick=()=>send("rotate-device",active());$("close-device").onclick=()=>send("toggle-device",active());
    window.addEventListener("keydown",(event)=>{const mod=event.metaKey||event.ctrlKey;if(event.ctrlKey&&event.key==="Tab"){event.preventDefault();send("cycle-tab",{direction:event.shiftKey?"-1":"1"})}else if(mod&&event.key.toLowerCase()==="l"){event.preventDefault();address.focus();address.select()}else if(mod&&event.key.toLowerCase()==="t"){event.preventDefault();send("new-tab")}else if(mod&&event.key.toLowerCase()==="w"){event.preventDefault();send("close-tab",active())}else if(mod&&event.key.toLowerCase()==="f"){event.preventDefault();send("open-find",active())}else if(mod&&event.key.toLowerCase()==="r"){event.preventDefault();send(event.shiftKey?"hard-reload":"reload",active())}});
    function active(){return{id:browserState?.activeTabId||""}}function send(action,params={}){const url=new URL("arivu-browser://"+action);for(const[key,value]of Object.entries(params))if(value!==undefined&&value!==null&&String(value)!=="")url.searchParams.set(key,String(value));window.location.href=url.href}function host(value){try{return new URL(value).hostname}catch{return""}}function security(value,state){if(state==="certificate-error")return{notSecure:true};try{const url=new URL(value);return{notSecure:url.protocol==="http:"&&!['localhost','127.0.0.1','::1'].includes(url.hostname)}}catch{return{notSecure:false}}}function rgbToHex(value){const match=String(value).match(/rgba?\\((\\d+)[, ]+(\\d+)[, ]+(\\d+)/i);if(!match)return /^#[0-9a-f]{6}$/i.test(value)?value:null;return"#"+[match[1],match[2],match[3]].map(part=>Number(part).toString(16).padStart(2,"0")).join("")}function showToast(message,error=false){clearTimeout(toastTimer);toast.textContent=message;toast.className="toast visible"+(error?" error":"");toastTimer=setTimeout(()=>toast.className="toast",3600)}
  </script>
</body></html>`;
}

function icon(name: string): string {
  const paths: Record<string, string> = {
    back: '<path d="m14 5-7 7 7 7"/>',
    forward: '<path d="m10 5 7 7-7 7"/>',
    reload: '<path d="M20 11a8 8 0 1 0-2.3 5.7"/><path d="M20 4v7h-7"/>',
    stop: '<path d="M7 7h10v10H7z"/>',
    plus: '<path d="M12 5v14M5 12h14"/>',
    close: '<path d="m7 7 10 10M17 7 7 17"/>',
    external: '<path d="M14 4h6v6M20 4l-9 9"/><path d="M18 13v6a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h6"/>',
    sliders: '<path d="M4 7h10M18 7h2M4 17h2M10 17h10"/><circle cx="16" cy="7" r="2"/><circle cx="8" cy="17" r="2"/>',
    warning: '<path d="M12 4 3.5 19h17L12 4Z"/><path d="M12 9v4M12 16h.01"/>',
    camera: '<path d="M4 8h3l2-3h6l2 3h3v11H4V8Z"/><circle cx="12" cy="13" r="3"/>',
    comment: '<path d="M5 5h14v10H9l-4 4V5Z"/>',
    download: '<path d="M12 3v12M7 10l5 5 5-5M5 20h14"/>',
    more: '<circle cx="5" cy="12" r="1" fill="currentColor" stroke="none"/><circle cx="12" cy="12" r="1" fill="currentColor" stroke="none"/><circle cx="19" cy="12" r="1" fill="currentColor" stroke="none"/>',
    rotate: '<path d="M20 7v5h-5"/><path d="M18.5 15A7 7 0 1 1 19 8l1 4"/>',
    up: '<path d="m7 14 5-5 5 5"/>',
    down: '<path d="m7 10 5 5 5-5"/>'
  };
  return `<svg viewBox="0 0 24 24" aria-hidden="true">${paths[name] ?? ""}</svg>`;
}
